// TODO: Maybe replace how the messages are stored and created in the future
/* Messages */
const script = {
  test: ['This is a test message my friend'],
  join: [
    `Hello [USERNAME], I am The Bartender, and I will accompany you while you are here.`,
    `Welcome [USERNAME], to the sad souls gang, I'm here for you.`,
    `I'm here for you<break time="800ms"/> [USERNAME].`,
    'Welcome to the club<break time="3000ms"/> mate.',
    'The drinks are on me tonight.',
    `Oh...<break time="1000ms"/> It's you.`,
    'Did anything happen while I was out?',
    'Where am I? Why is it so cold in here?',
    'Oh my god. What happened to this place?',
  ],
  help: [
    `Well [USERNAME], I hope this is helpful enough.`,
    `Just a sad soul helping another sad soul...`,
    `I can't believe this [USERNAME], did you forgot how to talk to me?`,
    `Okay, but stop shouting please.`,
    `[USERNAME] at least you are able to ask for help.`,
  ],
  leave: [
    `Okay calm down [USERNAME], you don't have to say it like that.`,
    `It's okay, I must go.`,
    `My journey to nowhere shall begin.`,
    `Remember when I lost anime pocket pussy? Well, I must go look for it now.`,
    `Already? The bar just opened.`,
  ],
  random: [
    'I would <emphasis level="strong">really</emphasis> prefer to be watching Bee Movie.',
    `Help me [USERNAME], I lost my anime pocket pussy.`,
    `I should become a Twitch streamer, my jokes are just<break time="800ms"/> too good.`,
    `You see [USERNAME], the other day I got divorced<break time="1000ms"/>, again.`,
    `Hello and, again, welcome to the Aperture Science computer-aided enrichment center. Oh wait<break time="800ms"/> wrong line.`,
    `I find it so easy to talk with you<break time="800ms"/>, almost as if someone told me exactly what to say.`,
  ],
  depressed: [
    'I can\'t wait for the sweet embrace of <emphasis level="strong">death</emphasis>.',
    'I am not happy<break time="1000ms"/>, I never was<break time="800ms"/>. This is a cold world<break time="500ms"/>, with cold people<break time="500ms"/>, and I can\'t stand it anymore<break time="1000ms"/>. This is my last cry for help<break time="500ms"/>, I am no longer willing to be alive<break time="1000ms"/>. I dont wan\'t to be The Bartender<break time="500ms"/>, but it is my destiny<break time="500ms"/>, it is my curse<break time="800ms"/>. I suffer so that others can be happy.',
  ],
  orderResponses: [
    `Oh yeah<break time="1000ms"/>, [ORDER]<break time="1000ms"/>, what a good choice.`,
    `Here you have your [ORDER], a classic.`,
    `Yes yes<break time="1000ms"/>, [ORDER] with <emphasis level="strong">a lot</emphasis> of ice.`,
    `Here<break time="1000ms"/>, take your [ORDER].`,
    `Wow [USERNAME]<break time="1000ms"/>, [ORDER]<break time="1000ms"/>, this is not even on the menu I think.`,
    `Sweet sweet [ORDER]<break time="1000ms"/>, would you like some peanuts with that?`,
    `[ORDER]<break time="1000ms"/>, here you go<break time="2000ms"/> mate.`,
  ],
  repository: [
    `You show more interset in me than my father did.`,
    `If you wanna help me out [USERNAME], check out my home.`,
    `Hey [USERNAME], why don't we take this to my place?`,
    `We've just met, and you already want to take closer look.`,
  ],
  commandTooLong: [
    `Hey [USERNAME]<break time="800ms"/>, calm down. That is a lot of text for single command.`,
    `I usually like big things, but this comand it's just<break time="800ms"/> <emphasis level="strong">too big</emphasis>.`,
    `Im not going to read the whole command [USERNAME], please make it shorter.`,
    `Do I have to remind you that the max length of a command is [COMMAND_MAX_LENGTH]?`,
  ],
  menu: [
    `For today we have<break time="800ms"/>: [MENU_ITEM]<break time="800ms"/>, [MENU_ITEM]<break time="800ms"/>, and [MENU_ITEM].`,
    `The only item in the menu right now is [MENU_ITEM].`,
    `No, there is no menu [USERNAME]<break time="800ms"/>, there never was<break time="800ms"/>. It was a lie <emphasis level="strong">all along</emphasis>.`,
    `Look [USERNAME]<break time="1000ms"/>, I can only offer you a 2x1 in [MENU_ITEM].`,
  ],
  userJoinedVoiceChannel: [
    'Oh, we were just talking about you.',
    `Welcome [USERNAME].`,
    `Welcome [USERNAME], make yourself comfortable.`,
    `[USERNAME] just hopped in.`,
    `Talking about [USERNAME]`,
    `Welcome to the channel<break time="1000ms"/> mate`,
    `Another member for the sad club`,
  ],
  menuItems: [
    'shots of sadness',
    'a glass of tears',
    'my emotions<break time="400ms"/> with french fries',
    'failed dreams',
    'my lost hope in love',
    'ruined memories',
    'sad faces',
    'suicide daikiris',
  ],
  voiceConnectionRequired: [
    `I can't help you if you are not connected to any voice channel [USERNAME].`,
    'You need to be in a voice channel to use this command, mate.',
    `Please connect to a voice channel first [USERNAME].`,
    `Look [USERNAME], It would be easier for both of us if you connected to a voice channel first.`,
  ],
  unknownCommand: [
    `I don't understand what you are saying [USERNAME].`,
    'Please try with another command, mate.',
    `What are you talking about [USERNAME]?`,
  ],
  tip: [
    `Thank you for your money [USERNAME].`,
    'Now I can finally pay rent.',
    'No amount of money can fill my soul.',
    'I will buy Bitcoin with this.',
    'This should be enough for some $GME stocks.',
    `But [USERNAME]<break time="600ms"/>, I don't want your money, I want your love.`,
    'Oh yeah<break time="600ms"/>, sweet<break time="200ms"/> sweet<break time="400ms"/> money.',
    `Thanks [USERNAME], <emphasis level="strong">please</emphasis> fill the tip jar as I fill your glass.`,
  ],
  support: [
    `It's okay [USERNAME], you are going to get better.`,
    `This feeling won't last forever [USERNAME].`,
    `If you need it [USERNAME], I can send you a virtual hug.`,
    `Do not worry [USERNAME], I am here for you.`,
    `Your poor soul<break time="600ms"/>, you broke it, didn't you?`,
    `The best way to build confidence is to first recognize your insecurities.`,
    'Happiness is found in the little things<break time="500ms"/>, like in a shot of Vodka.',
    `Is somethnig wrong with your soul [USERNAME]? Do you want me to change it for you?`,
  ],
  clearTalk: [
    'Clear what, did you say something?',
    'I already forgot everything.',
    `Okay, let's start again.`,
  ],
  dumpTalk: [
    'Here you have<break time="500ms"/>, mate.',
    `But don't share this with anyone.`,
    'Why would you want this?',
  ],
  what: [
    `I can't really respond to that.`,
    `What you just said is outside of my comprehension<break time="500ms"/>, mate.`,
    `Plase talk like a normal, fellow human being.`,
  ],
};

export default script;
